In [66]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [67]:
# **Q1.1:** Create a 4x4 identity matrix using `np.eye()`
import numpy as np
import math
data=np.eye(4)
data

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
# **Q1.2:** Create an array of 8 zeros using `np.zeros()`
data=np.zeros(8)
data

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
# **Q1.4:** Create an array with values from 0 to 15 using `np.arange()`
data=np.ones(6)
data

array([1., 1., 1., 1., 1., 1.])

In [70]:
# **Q1.5:** Create an array with 8 evenly spaced values from 0 to 100 using `np.linspace()`
data=np.arange(0,15)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [71]:
L=np.linspace(0,100,(8))
L

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [72]:
# **Q2.1:** What is the shape of the `banking_data` array?
import numpy as np

bd = np.array([
    [1, 5230, 720, 34, 3],
    [2, 12400, 810, 21, 7],
    [3, 230, 580, 15, 1],
    [4, 8900, 765, 45, 5],
    [5, 15300, 840, 60, 10],
    [6, 320, 495, 9, 0],
    [7, 6780, 710, 28, 4],
    [8, 2150, 630, 18, 2],
    [9, 11675, 775, 40, 6],
    [10, 980, 660, 12, 1]
])

bd.shape

(10, 5)

In [73]:
# **Q2.2:** What is the data type of the `banking_data` array?
type(bd)

numpy.ndarray

In [74]:
# **Q2.3:** What is the size (total number of elements) of the `banking_data` array?
bd.size

50

In [75]:
# **Q2.4:** What is the number of dimensions of the `banking_data` array?
bd.ndim

2

In [76]:
# **Q2.5:** What is the memory size of the `banking_data` array in bytes?
bd.nbytes

400

In [77]:

# **Q3.1:** Extract the first row of `banking_data`
bd[0,:]

array([   1, 5230,  720,   34,    3])

In [78]:

# **Q3.2:** Extract the last row of `banking_data`
bd[9,:]

array([ 10, 980, 660,  12,   1])

In [79]:
# **Q3.3:** Extract the Account_Balance column (column index 1)
bd[:,1]

array([ 5230, 12400,   230,  8900, 15300,   320,  6780,  2150, 11675,
         980])

In [80]:
# **Q3.4:** Extract the first 4 rows and first 3 columns
bd[0:4,0:3]

array([[    1,  5230,   720],
       [    2, 12400,   810],
       [    3,   230,   580],
       [    4,  8900,   765]])

In [81]:
# **Q3.5:** Extract rows 3 to 7 (inclusive)
bd[2:7,:]

array([[    3,   230,   580,    15,     1],
       [    4,  8900,   765,    45,     5],
       [    5, 15300,   840,    60,    10],
       [    6,   320,   495,     9,     0],
       [    7,  6780,   710,    28,     4]])

In [82]:
# **Q4.1:** Calculate the sum of all account balances
S=bd[:,1].sum()
S


np.int64(63965)

In [83]:
# **Q4.2:** Calculate the mean account balance
Mean=np.mean(bd[:,1])
Mean

np.float64(6396.5)

In [84]:
# **Q4.3:** Calculate the standard deviation of account balances
std=np.std(bd[:,1])
std

np.float64(5227.552032261372)

In [85]:
# **Q4.4:** Calculate the variance of account balances
var=np.var(bd[:,1])
var

np.float64(27327300.25)

In [86]:
# **Q4.5:** Calculate the median account balance
M=np.median(bd[:,1])
M

np.float64(6005.0)

In [87]:
# **Q5.1:** Find the minimum and maximum account balances
min=bd[:,1].min()
max=bd[:,1].max()
min,max

(np.int64(230), np.int64(15300))

In [88]:
# **Q5.2:** Find the minimum and maximum credit scores
min=bd[:,2].min()
max=bd[:,2].max()
min,max

(np.int64(495), np.int64(840))

In [89]:
# **Q5.3:** Calculate the percentile values for account balances (25th, 50th, 75th)
perct=np.percentile(bd[:,1],[25,50,75])
perct

array([ 1272.5 ,  6005.  , 10981.25])

In [90]:
# **Q5.4:** Calculate the correlation between account balance and credit score
cor=np.corrcoef(bd[:,1],bd[:,2])
cor

array([[1.        , 0.92346792],
       [0.92346792, 1.        ]])

In [91]:
# **Q5.5:** Calculate the covariance between account balance and credit score
cova=np.cov(bd[:,1],bd[:,2])
cova

array([[3.03636669e+07, 5.49508056e+05],
       [5.49508056e+05, 1.16613889e+04]])

In [92]:
# **Q6.1:** Reshape the `banking_data` to 5 rows × 10 columns
bd.reshape(5,10)

array([[    1,  5230,   720,    34,     3,     2, 12400,   810,    21,
            7],
       [    3,   230,   580,    15,     1,     4,  8900,   765,    45,
            5],
       [    5, 15300,   840,    60,    10,     6,   320,   495,     9,
            0],
       [    7,  6780,   710,    28,     4,     8,  2150,   630,    18,
            2],
       [    9, 11675,   775,    40,     6,    10,   980,   660,    12,
            1]])

In [93]:
# **Q6.2:** Flatten the `banking_data` to a 1D array


In [94]:
# **Q6.3:** Transpose the `banking_data`
bd.T

array([[    1,     2,     3,     4,     5,     6,     7,     8,     9,
           10],
       [ 5230, 12400,   230,  8900, 15300,   320,  6780,  2150, 11675,
          980],
       [  720,   810,   580,   765,   840,   495,   710,   630,   775,
          660],
       [   34,    21,    15,    45,    60,     9,    28,    18,    40,
           12],
       [    3,     7,     1,     5,    10,     0,     4,     2,     6,
            1]])

In [95]:
# **Q6.4:** Split the `banking_data` into 2 equal parts vertically
half=np.vsplit(bd,2)
half

[array([[    1,  5230,   720,    34,     3],
        [    2, 12400,   810,    21,     7],
        [    3,   230,   580,    15,     1],
        [    4,  8900,   765,    45,     5],
        [    5, 15300,   840,    60,    10]]),
 array([[    6,   320,   495,     9,     0],
        [    7,  6780,   710,    28,     4],
        [    8,  2150,   630,    18,     2],
        [    9, 11675,   775,    40,     6],
        [   10,   980,   660,    12,     1]])]

In [96]:
half_hor=np.hsplit(bd,5)
half_hor

[array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 array([[ 5230],
        [12400],
        [  230],
        [ 8900],
        [15300],
        [  320],
        [ 6780],
        [ 2150],
        [11675],
        [  980]]),
 array([[720],
        [810],
        [580],
        [765],
        [840],
        [495],
        [710],
        [630],
        [775],
        [660]]),
 array([[34],
        [21],
        [15],
        [45],
        [60],
        [ 9],
        [28],
        [18],
        [40],
        [12]]),
 array([[ 3],
        [ 7],
        [ 1],
        [ 5],
        [10],
        [ 0],
        [ 4],
        [ 2],
        [ 6],
        [ 1]])]

In [97]:
# **Q7.1:** Find customers with account balance greater than $100,000
find=bd[bd[:,1]>100000]
find

array([], shape=(0, 5), dtype=int64)

In [98]:
# **Q7.2:** Find customers with credit score greater than 800
Cs=bd[bd[:,2]>800]
Cs

array([[    2, 12400,   810,    21,     7],
       [    5, 15300,   840,    60,    10]])

In [99]:
# **Q7.3:** Find customers with transaction count greater than 50 AND credit score less than 750
FC=bd[(bd[:,3]>50) & (bd[:,2]>750)]
FC

array([[    5, 15300,   840,    60,    10]])

In [100]:
# **Q7.4:** Count how many customers have account balance between $10,000 and $100,000
count=np.sum((bd[:,1]>10000) & (bd[:,1]<1000000))
count

np.int64(3)

In [101]:
# **Q7.5:** Find the index of the customer with the highest credit score
High_CB=bd[:,2].argmax()+1
High_CB

np.int64(5)

In [102]:
# **Q8.1:** Sort the `banking_data` by account balance (ascending)
AS=np.argsort(bd[:,1])+1
AS

array([ 3,  6, 10,  8,  1,  7,  4,  9,  2,  5])

In [103]:
# **Q8.2:** Sort the `banking_data` by credit score (descending)
DS=(-bd[:,4]).argsort()+1
DS

array([ 5,  2,  9,  4,  7,  1,  8,  3, 10,  6])

In [104]:
# **Q8.3:** Find the indices that would sort the array by years active
Years_active=bd[:,4].argsort()+1
Years_active

array([ 6,  3, 10,  8,  1,  7,  4,  9,  2,  5])

In [105]:
# **Q8.4:** Find the customer with the second highest account balance
AS=np.argsort(bd[:,1])+1
AS[1]


np.int64(6)

In [106]:
# **Q8.5:** Find the customer with the lowest transaction count
Low_tran=np.argsort(bd[:,3])+1
Low_tran[0]

np.int64(6)

In [107]:
# **Q9.1:** Calculate the absolute values of all elements
A=abs(bd)
A

array([[    1,  5230,   720,    34,     3],
       [    2, 12400,   810,    21,     7],
       [    3,   230,   580,    15,     1],
       [    4,  8900,   765,    45,     5],
       [    5, 15300,   840,    60,    10],
       [    6,   320,   495,     9,     0],
       [    7,  6780,   710,    28,     4],
       [    8,  2150,   630,    18,     2],
       [    9, 11675,   775,    40,     6],
       [   10,   980,   660,    12,     1]])

In [108]:
# **Q9.2:** Calculate the square root of all account balances
Root=np.sqrt(bd[:,1])
Root

array([ 72.31873893, 111.35528726,  15.16575089,  94.33981132,
       123.69316877,  17.88854382,  82.3407554 ,  46.36809248,
       108.05091392,  31.30495168])

In [109]:
# **Q9.3:** Calculate the square of all credit scores
Root=np.sqrt(bd[:,2])
Root

array([26.83281573, 28.46049894, 24.08318916, 27.65863337, 28.98275349,
       22.24859546, 26.64582519, 25.0998008 , 27.83882181, 25.69046516])

In [110]:
# **Q9.4:** Calculate the exponential of all transaction counts
EXP=np.exp(bd[:,3])
EXP

array([5.83461743e+14, 1.31881573e+09, 3.26901737e+06, 3.49342711e+19,
       1.14200739e+26, 8.10308393e+03, 1.44625706e+12, 6.56599691e+07,
       2.35385267e+17, 1.62754791e+05])

In [111]:
# **Q9.5:** Calculate the natural logarithm of all account balances
Log=np.log(bd[:,1])
Log

array([8.56216656, 9.42545175, 5.43807931, 9.09380656, 9.63560811,
       5.768321  , 8.82173238, 7.67322312, 9.36520508, 6.88755257])

In [112]:
# **Q10.1:** Calculate the cumulative sum of account balances
CSum=np.cumsum(bd[:,1])
CSum

array([ 5230, 17630, 17860, 26760, 42060, 42380, 49160, 51310, 62985,
       63965])

In [113]:
# **Q10.2:** Calculate the cumulative product of transaction counts
CPro=np.cumprod(bd[:,3])
CPro

array([            34,            714,          10710,         481950,
             28917000,      260253000,     7287084000,   131167512000,
        5246700480000, 62960405760000])

In [114]:
# **Q10.3:** Calculate the difference between consecutive account balances
Condiff=np.diff(bd[:,1])
Condiff

array([  7170, -12170,   8670,   6400, -14980,   6460,  -4630,   9525,
       -10695])

In [115]:
# **Q10.4:** Calculate the gradient of account balances
Grad=np.gradient(bd[:,1])
Grad

array([  7170. ,  -2500. ,  -1750. ,   7535. ,  -4290. ,  -4260. ,
          915. ,   2447.5,   -585. , -10695. ])

In [116]:
# **Q10.5:** Calculate the histogram of account balances with 5 bins
His=np.histogram(bd[:,1], bins=5)
His

(array([4, 1, 2, 1, 2]),
 array([  230.,  3244.,  6258.,  9272., 12286., 15300.]))

In [117]:
# **Q11.1:** Generate 6 random integers between 1 and 1000
random=np.random.randint(0,1000,6)
random

array([595, 106, 123, 569, 214, 737], dtype=int32)

In [118]:
# **Q11.2:** Generate 6 random floats between 0 and 1
ranfloat=np.random.rand(6)
ranfloat

array([0.68482974, 0.4809319 , 0.39211752, 0.34317802, 0.72904971,
       0.43857224])

In [119]:
# **Q11.3:** Generate 6 random numbers from normal distribution (mean=700, std=100)
Normal=np.random.normal(700,100,6)
Normal

array([685.66275259, 638.08090993, 623.05665285, 757.67460214,
       712.65259202, 569.85110255])

In [120]:
bd

array([[    1,  5230,   720,    34,     3],
       [    2, 12400,   810,    21,     7],
       [    3,   230,   580,    15,     1],
       [    4,  8900,   765,    45,     5],
       [    5, 15300,   840,    60,    10],
       [    6,   320,   495,     9,     0],
       [    7,  6780,   710,    28,     4],
       [    8,  2150,   630,    18,     2],
       [    9, 11675,   775,    40,     6],
       [   10,   980,   660,    12,     1]])

In [121]:
# **Q11.4:** Shuffle the `banking_data` rows randomly
suffle =bd.copy()
np.random.shuffle(suffle)
suffle

array([[    8,  2150,   630,    18,     2],
       [    3,   230,   580,    15,     1],
       [   10,   980,   660,    12,     1],
       [    7,  6780,   710,    28,     4],
       [    4,  8900,   765,    45,     5],
       [    2, 12400,   810,    21,     7],
       [    1,  5230,   720,    34,     3],
       [    6,   320,   495,     9,     0],
       [    9, 11675,   775,    40,     6],
       [    5, 15300,   840,    60,    10]])

In [122]:
# **Q11.5:** Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
L=np.random.random(4)
L

array([0.69646919, 0.28613933, 0.22685145, 0.55131477])

In [123]:
# **Q12.1:** Calculate the dot product of account balance and credit score columns
DP=np.dot(bd[:,1],bd[:,2])


In [124]:
# **Q12.2:** Calculate the cross product of first two rows
Cross=np.cross(bd[0,:3],bd[1,:3])
Cross

array([-4691700,      630,     1940])

In [125]:
# **Q12.3:** Calculate the norm (magnitude) of the account balance column
Mag=np.linalg.norm(bd[:,1])
Mag

np.float64(26123.26788516322)

In [126]:
# **Q12.4:** Create a 3x3 matrix and calculate its determinant
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
Det=np.linalg.det(m)
m,Det

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 np.float64(0.0))

In [136]:
# **Q12.5:** Calculate the inverse of the 3x3 matrix
a=np.random.randint(1,10,(3,3))
b=np.linalg.inv(a)
b

array([[ 0.21296296, -0.16666667,  0.00925926],
       [ 0.16666667,  0.        , -0.16666667],
       [-0.48148148,  0.33333333,  0.37037037]])

In [ ]:
# **Q13.1:** Convert all customer IDs to strings
S=bd[:,0].astype(str)
S


array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [ ]:
# **Q13.2:** Check if any customer ID contains '100'
cont = np.char.find(S, '100') >= 0
cont

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
# **Q13.3:** Convert all customer IDs to uppercase (if they were strings)
upper=np.char.upper(S)
S

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [ ]:
# **Q13.4:** Count the length of each customer ID string
len=np.char.str_len(S)
len

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2])

In [ ]:
# **Q13.5:** Replace '100' with 'CUST' in customer IDs
re=np.char.replace(S,'100','cust')
re

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U2')

In [ ]:
# **Q14.1:** Convert years active to months
months=bd[:,4]*12
months

array([ 36,  84,  12,  60, 120,   0,  48,  24,  72,  12])

In [ ]:
# **Q14.2:** Calculate the average years active
mean=bd[:,4].mean()
mean

np.float64(3.9)

In [ ]:
# **Q14.3:** Find customers who have been active for more than 5 years
more=bd[bd[:,4]>5]
more

array([[    2, 12400,   810,    21,     7],
       [    5, 15300,   840,    60,    10],
       [    9, 11675,   775,    40,     6]])

In [ ]:
# **Q14.4:** Calculate the total time all customers have been active (in years)
All=bd[:,4].sum()
All

np.int64(39)

In [ ]:
# **Q14.5:** Find the customer with the shortest time active
short=bd[:,4].argmin()+1
short

np.int64(6)

In [ ]:
# **Q15.1:** Apply a function to calculate 5% interest on all account balances
d=bd[:,1]*0.05
c=(bd[:,1])+d
print(c)



[ 5491.5  13020.     241.5   9345.   16065.     336.    7119.    2257.5
 12258.75  1029.  ]


In [ ]:
# **Q15.2:** Use `np.where` to categorize customers by balance ranges
CC=np.where(bd[:,1]>6396,"High value","Low value")
CC

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)

In [ ]:
# **Q15.3:** Use `np.select` to categorize customers by credit score ranges
range=[
    bd[:,2]<400,                                         
    (bd[:,2] >=400) & (bd[:,2]<700),
    bd[:,2]>=700
]
choices=['low','good','excellent']
customer=np.select(range,choices,default='unknowen')
print(customer)


['excellent' 'excellent' 'good' 'excellent' 'excellent' 'good' 'excellent'
 'good' 'excellent' 'good']


In [150]:
# **Q15.4:** Use `np.piecewise` to apply different interest rates based on balance
bd[:,1]
def low_balance(x): return x*0.5 
def normal_balance(x): return x*1.0
def high_balance(x): return x*0.5

interest=np.piecewise(bd[:,1],
                   [bd[:,1]<20,
                   (bd[:,1]>=20) & (bd[:,1]<50),
                   bd[:,1]>=50],
                   [low_balance,normal_balance,high_balance])
print(interest)

[2615 6200  115 4450 7650  160 3390 1075 5837  490]


In [151]:
# **Q15.5:** Use `np.apply_along_axis` to calculate the sum of each row
bd
sum_of_row=np.apply_along_axis(np.sum,1,bd) 
print(sum_of_row)


[ 5988 13240   829  9719 16215   830  7529  2808 12505  1663]


In [152]:
# **Q16.1:** Concatenate two arrays horizontally using `np.hstack()`
n=np.random.randint(1,10,(3))
m=np.random.randint(1,10,(3))
o=np.hstack([n,m])
n,m,o



(array([7, 3, 5], dtype=int32),
 array([5, 7, 4], dtype=int32),
 array([7, 3, 5, 5, 7, 4], dtype=int32))

In [154]:
# **Q16.5:** Create a column stack using `np.column_stack()`
a=np.random.randint(1,10,(3,1))
b=np.random.randint(1,10,(3,1))
c=np.hstack([a,b])
a,b,c

(array([[2],
        [6],
        [8]], dtype=int32),
 array([[3],
        [5],
        [9]], dtype=int32),
 array([[2, 3],
        [6, 5],
        [8, 9]], dtype=int32))

In [ ]:
# nQ16.2: Concatenate two arrays vertically using np.vstack()
l=np.random.randint(1,10,(1,3))
m=np.random.randint(1,10,(1,3))
n=np.vstack([l,m])
l,m,n



Q16.2: Concatenate two arrays vertically using np.vstack()


(array([[2, 3, 2]], dtype=int32),
 array([[2, 4, 6]], dtype=int32),
 array([7, 3, 5], dtype=int32))

In [156]:
# **Q16.3:** Concatenate arrays along a specific axis using `np.concatenate()`
l=np.random.randint(1,10,(1,3))
m=np.random.randint(1,10,(1,3))
h=np.concatenate([l,m])
l,m,

(array([[1, 9, 2]], dtype=int32), array([[7, 4, 4]], dtype=int32))

In [157]:
# '**Q16.4:** Stack arrays depth-wise using `np.dstack()`
a=np.random.randint(1,10,(1,3))
b=np.random.randint(1,10,(1,3))
G=np.dstack([a,b])
a,b,G

(array([[6, 8, 3]], dtype=int32),
 array([[4, 4, 4]], dtype=int32),
 array([[[6, 4],
         [8, 4],
         [3, 4]]], dtype=int32))

In [163]:
# **Q16.5:** Create a column stack using `np.column_stack()`
a=np.random.randint(1,10,(1,3))
b=np.random.randint(1,10,(1,3))
data=np.column_stack([a,b])
print(a)
print(b)
print(data)

[[2 4 5]]
[[8 7 2]]
[[2 4 5 8 7 2]]


In [165]:
# **Q17.1:** Split an array into 3 equal parts using `np.split()`
s1=np.array([1,2,3,4,5,6,7,8,9])
s2=np.split(str,3)
print(s1)
for i ,part in enumerate(s2):
    print(f"{i+1}:{part}")

[1 2 3 4 5 6 7 8 9]
1:[1 2 3]
2:[4 5 6]
3:[7 8 9]


In [173]:
# **Q17.2:** Split an array at specific indices using `np.split()`
s=np.random.randint(1,10,(1,1))
str=np.split(s,[4,8])
print(str)

[array([[7]], dtype=int32), array([], shape=(0, 1), dtype=int32), array([], shape=(0, 1), dtype=int32)]


In [174]:
# **Q17.3:** Split an array horizontally using `np.hsplit()`
str=np.array([1,2,3,5,6,7])
sp=np.hsplit(str,3)
for i ,part in enumerate(sp):
    print(f"{i+1},{part}")

1,[1 2]
2,[3 5]
3,[6 7]


In [175]:
# **Q17.4:** Split an array vertically using `np.vsplit()`
str=np.array([[1,2,3],[5,6,7]])
split_ver=np.vsplit(str,2)
for i ,part in enumerate(split_ver):
    print(f"{i+1},{part}")


1,[[1 2 3]]
2,[[5 6 7]]


In [176]:
# **Q17.5:** Split an array into equal chunks using `np.array_split()`
data=np.array([1,2,3,4,5,6,7,8,9,20])
split_array=np.array_split(data,4)
for i ,part in enumerate(split_array):
    print(f"{i+1},{part}")

1,[1 2 3]
2,[4 5 6]
3,[7 8]
4,[ 9 20]


In [177]:
# **Q18.1:** Repeat each element of an array 3 times using `np.repeat()`
data=np.array([1,2,3,4,5])
repeat=np.repeat(data,3)
data,repeat


(array([1, 2, 3, 4, 5]), array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5]))

In [179]:
# **Q18.2:** Repeat an entire array 2 times using `np.tile()`
repeat_two=np.tile(data,2)
data,repeat_two


(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5]))

In [180]:
# **Q18.3:** Repeat a 2D array using `np.tile()`
array_2D=np.random.randint(1,10,(2,2))
data=np.tile(array_2D,(2,2))
array_2D,data

(array([[9, 7],
        [5, 5]], dtype=int32),
 array([[9, 7, 9, 7],
        [5, 5, 5, 5],
        [9, 7, 9, 7],
        [5, 5, 5, 5]], dtype=int32))

In [181]:
# **Q18.4:** Create a pattern using `np.tile()`
array=np.array([1,0])
aptt=np.tile(array,(6,6))
array,aptt


(array([1, 0]),
 array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]]))

In [184]:
# **Q18.5:** Repeat elements with different counts using `np.repeat()`
b=[2,3]
repeat=np.repeat(array,b)
array,b,repeat

(array([1, 0]), [2, 3], array([1, 1, 0, 0, 0]))

In [185]:
# **Q19.1:** Compare two arrays for equality using `np.array_equal()`
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
comp=np.array_equal(a,b)
comp
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,1,2])
Z=np.array_equal(a,b)
Z


True

In [186]:

# **Q19.2:** Check if arrays are close using `np.allclose()`
a=np.array([1,2,3,4,5,6])
b=np.array([5,6,7,8,9,10])
close=np.allclose(a,b,atol=4) 
a,b,close

(array([1, 2, 3, 4, 5, 6]), array([ 5,  6,  7,  8,  9, 10]), True)

In [187]:
# **Q19.3:** Apply logical AND operation between arrays
AND=np.logical_and(a>0 , a<6)
print(a)
print(AND)

[1 2 3 4 5 6]
[ True  True  True  True  True False]


In [189]:
# **Q19.4:** Apply logical OR operation between arrays
OR=np.logical_or(b==2,b==6)
print(b)
print(OR)

[ 5  6  7  8  9 10]
[False  True False False False False]


In [190]:
# **Q19.5:** Apply logical NOT operation to an array
NOT=np.logical_not(a!=1)
print(c)
print(NOT)

[[2 3]
 [6 5]
 [8 9]]
[ True False False False False False]


In [191]:
# **Q20.1:** Find unique elements in an array using `np.unique()`
b=np.array([1,1,2,2,3,3,4,4,4,4,4,7,7,7])
a=np.unique(b)
print(a)

[1 2 3 4 7]


In [192]:
# **Q20.2:** Find the intersection of two arrays using `np.intersect1d()`
a=np.array([1,2,3,4,5])
b=np.array([1,3,2,5,7])    
inter=np.intersect1d(a,b)
print(inter)

[1 2 3 5]


In [195]:
# **Q20.3:** Find the union of two arrays using `np.union1d()`
union=np.union1d(a,b)
a,b,union

(array([1, 2, 3, 4, 5]), array([1, 3, 2, 5, 7]), array([1, 2, 3, 4, 5, 7]))

In [196]:
# **Q20.4:** Find elements in first array but not in second using `np.setdiff1d()`
ele=np.setdiff1d(a,b)
a,b,ele

(array([1, 2, 3, 4, 5]), array([1, 3, 2, 5, 7]), array([4]))

In [197]:
# **Q20.5:** Find the symmetric difference between two arrays using `np.setxor1d()`
symmtric_diff=np.setxor1d(a,b)
a,b,symmtric_diff

(array([1, 2, 3, 4, 5]), array([1, 3, 2, 5, 7]), array([4, 7]))