In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
rd = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

In [6]:
rd
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [7]:
# ## Basic Performance Analysis
# 1. What is the **total revenue** generated across all stores?
# 2. Which store recorded the **highest sales**?
# 3. Which store recorded the **lowest sales**?
# 4. What is the **average daily sales** per store?
# 5. How many stores achieved sales **above ₹35,000**?

# ## Customer Insights
# 6. Which store had the **highest customer footfall**?
# 7. What is the **average number of customers** per store?
# 8. How many stores have **more than 450 customers**?
# 9. Which store has the **lowest customer count**?
# 10. Is there any store where **high sales do not correspond to high customers**?

# ## Inventory & Returns Analysis
# 11. What is the **total inventory** across all stores?
# 12. Which store has the **highest inventory stock**?
# 13. How many stores have **inventory less than 1300 units**?
# 14. Which store has the **highest return rate** (returns ÷ inventory)?
# 15. Which stores have **returns greater than 15 units**?

# ## Sales & Customer Correlation
# 16. Is there a **positive correlation** between sales and customers?
# 17. Which store has **high customer visits but low sales**?
# 18. Which store has **low customers but high sales**?
# 19. How many stores have **sales per customer above ₹90**?
# 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

# ## Profitability & Growth
# 21. If profit margin is **20% of sales**, what is the **profit per store**?
# 22. Which store has the **highest profit**?
# 23. Which store has the **lowest profit**?
# 24. If sales increase by **10% next month**, what are the **new sales figures**?
# 25. How will **total profit** change with the 10% sales increase?

# ## Operational Strategy
# 26. Which stores need **inventory restocking** based on sales and current stock?
# 27. Which stores show **high returns percentage** and might require **quality checks**?
# 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
# 29. Which store is the **worst performer overall**?
# 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?

In [8]:
# 1. What is the **total revenue** generated across all stores?
revenue=rd[:,4].sum()
revenue


np.int64(142)

In [9]:
# 2. Which store recorded the **highest sales**?
highest_sales=rd[:,1].argmax()+1
highest_sales

np.int64(9)

In [10]:
# 3. Which store recorded the **lowest sales**?
lowest_sales=rd[:,1].argmin()+1
lowest_sales

np.int64(1)

In [11]:
# 4. What is the **average daily sales** per store?
avg_sales=rd[:,1].mean()/10
avg_sales

np.float64(3350.0)

In [12]:
# 5. How many stores achieved sales **above ₹35,000**?
above=rd[rd[:,1]>35000]
above[:,0]


array([4, 7, 9])

In [13]:
#  6. Which store had the **highest customer footfall**?
C=rd[:,2].argmax()+1
C


np.int64(9)

In [14]:
# 7. What is the **average number of customers** per store?
avgper_cust=rd[:,2].mean()/10
avgper_cust

np.float64(42.5)

In [15]:
# 8. How many stores have **more than 450 customers**?
more=rd[rd[:,2]>450]
more


array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])

In [16]:
# 9. Which store has the **lowest customer count**?
lowest=rd[:,2].argmin()+1
lowest

np.int64(1)

In [17]:
# 10. Is there any store where **high sales do not correspond to high customers**?
A=rd[:,1].mean()
B=rd[:,2].mean()
C=rd[(rd[:,1]>A) & (rd[:,2]<B)]
C

array([[    5, 35000,   420,  1400,    12]])

In [18]:
# 11. What is the **total inventory** across all stores?
total_inventry=rd[:,3].sum()
total_inventry

np.int64(14300)

In [19]:
# 12. Which store has the **highest inventory stock**?
higgest_inventry=rd[:,3].argmax()+1
higgest_inventry

np.int64(9)

In [20]:
# 13. How many stores have **inventory less than 1300 units**?
lowest_in=rd[rd[:,3]<1300]
lowest_in[:,0]

array([1, 3, 8])

In [21]:
# 14. Which store has the **highest return rate** (returns ÷ inventory)?
higgest_return=(rd[:,4]/rd[:,3]).argmax()+1
higgest_inventry


np.int64(9)

In [22]:
# 15. Which stores have **returns greater than 15 units**?
return_greater=rd[rd[:,4]>15]
return_greater[:,0]

array([4, 7, 9])

In [23]:
# 16. Is there a **positive correlation** between sales and customers?
corr=np.corrcoef(rd[:,1]/rd[:,2])
corr

np.float64(1.0)

In [24]:
# 17. Which store has **high customer visits but low sales**?
A=rd[:,1].mean()
B=rd[:,2].mean()
C=rd[(rd[:,1]<A) & (rd[:,2]>B)]
C

array([[    2, 32000,   450,  1500,    15]])

In [25]:
# 18. Which store has **low customers but high sales**?
A=rd[:,1].mean()
B=rd[:,2].mean()
C=rd[(rd[:,1]>A) & (rd[:,2]<B)]
C

array([[    5, 35000,   420,  1400,    12]])

In [26]:
# 19. How many stores have **sales per customer above ₹90**?
H=rd[:,1]/rd[:,2]
H[H>90]


array([], dtype=float64)

In [27]:
# 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
A=rd[:,3].mean()
B=rd[:,2].mean()
C=rd[(rd[:,3]>A) & (rd[:,2]<B)]
C

array([[   10, 33000,   410,  1450,    11]])

In [28]:
# 21. If profit margin is **20% of sales**, what is the **profit per store**?
P=rd[:,1]*0.20
P

array([5000., 6400., 5600., 8200., 7000., 5400., 7800., 6000., 9000.,
       6600.])

In [29]:
# 22. Which store has the **highest profit**?
HP=(rd[:,1]-rd[:,4]).argmax()+1
HP

np.int64(9)

In [30]:
# 23. Which store has the **lowest profit**?
LP=(rd[:,1]-rd[:,4]).argmin()+1
LP

np.int64(1)

In [31]:
# 24. If sales increase by **10% next month**, what are the **new sales figures**?
P=rd[:,1]*0.10
Q=rd[:,1]+P
Q



array([27500., 35200., 30800., 45100., 38500., 29700., 42900., 33000.,
       49500., 36300.])

In [32]:
# 25. How will **total profit** change with the 10% sales increase?
totat_profit=sum(Q)
totat_profit

np.float64(368500.0)

In [33]:
# 26. Which stores need **inventory restocking** based on sales and current stock?
avg_sales=rd[:,1].mean()
avg_inv=rd[:,3].mean()
RS=rd[(rd[:,1]>avg_sales) & (rd[:,3]<avg_inv)]
RS


array([[    5, 35000,   420,  1400,    12]])

In [34]:
# 27. Which stores show **high returns percentage** and might require **quality checks**?


In [35]:
# 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?


In [36]:
# 29. Which store is the **worst performer overall**?


In [37]:
# 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?